/**
 * West Coast Informatics Terminology API
 * API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Metadata model module.
 * @module model/Metadata
 * @version 1.0.0
 */
class Metadata {
    /**
     * Constructs a new <code>Metadata</code>.
     * Represents a named metadata entry
     * @alias module:model/Metadata
     * @param type {String} the type of metadata
     * @param abbreviation {String} the label for the metadata element
     * @param name {String} the name
     * @param terminology {String} the terminology abbreviation
     * @param created {Date} the created date
     * @param local {Boolean} indicates whether this data element was created by local editing
     * @param modifiedBy {String} the identifier of the user who made the last modification
     * @param modified {Date} the last modified date
     * @param id {String} the unique identifier
     * @param active {Boolean} indicates whether or not this data element is active
     */
    constructor(type, abbreviation, name, terminology, created, local, modifiedBy, modified, id, active) { 
        
        Metadata.initialize(this, type, abbreviation, name, terminology, created, local, modifiedBy, modified, id, active);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, abbreviation, name, terminology, created, local, modifiedBy, modified, id, active) { 
        obj['type'] = type;
        obj['abbreviation'] = abbreviation;
        obj['name'] = name;
        obj['terminology'] = terminology;
        obj['created'] = created;
        obj['local'] = local;
        obj['modifiedBy'] = modifiedBy;
        obj['modified'] = modified;
        obj['id'] = id;
        obj['active'] = active;
    }

    /**
     * Constructs a <code>Metadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Metadata} obj Optional instance to populate.
     * @return {module:model/Metadata} The populated <code>Metadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Metadata();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('abbreviation')) {
                obj['abbreviation'] = ApiClient.convertToType(data['abbreviation'], 'String');
            }
            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('terminology')) {
                obj['terminology'] = ApiClient.convertToType(data['terminology'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': 'String'});
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('local')) {
                obj['local'] = ApiClient.convertToType(data['local'], 'Boolean');
            }
            if (data.hasOwnProperty('modifiedBy')) {
                obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Metadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Metadata</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Metadata.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['abbreviation'] && !(typeof data['abbreviation'] === 'string' || data['abbreviation'] instanceof String)) {
            throw new Error("Expected the field `abbreviation` to be a primitive type in the JSON string but got " + data['abbreviation']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['terminology'] && !(typeof data['terminology'] === 'string' || data['terminology'] instanceof String)) {
            throw new Error("Expected the field `terminology` to be a primitive type in the JSON string but got " + data['terminology']);
        }
        // ensure the json data is a string
        if (data['modifiedBy'] && !(typeof data['modifiedBy'] === 'string' || data['modifiedBy'] instanceof String)) {
            throw new Error("Expected the field `modifiedBy` to be a primitive type in the JSON string but got " + data['modifiedBy']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

Metadata.RequiredProperties = ["type", "abbreviation", "name", "terminology", "created", "local", "modifiedBy", "modified", "id", "active"];

/**
 * the type of metadata
 * @member {String} type
 */
Metadata.prototype['type'] = undefined;

/**
 * the label for the metadata element
 * @member {String} abbreviation
 */
Metadata.prototype['abbreviation'] = undefined;

/**
 * used for when metadata lists need to be ranked (as in a ranked list of term types)
 * @member {Number} rank
 */
Metadata.prototype['rank'] = undefined;

/**
 * the name
 * @member {String} name
 */
Metadata.prototype['name'] = undefined;

/**
 * the terminology abbreviation
 * @member {String} terminology
 */
Metadata.prototype['terminology'] = undefined;

/**
 * key/value pairs associated with this object. Entries in this map are terminology-specific
 * @member {Object.<String, String>} attributes
 */
Metadata.prototype['attributes'] = undefined;

/**
 * the created date
 * @member {Date} created
 */
Metadata.prototype['created'] = undefined;

/**
 * indicates whether this data element was created by local editing
 * @member {Boolean} local
 */
Metadata.prototype['local'] = undefined;

/**
 * the identifier of the user who made the last modification
 * @member {String} modifiedBy
 */
Metadata.prototype['modifiedBy'] = undefined;

/**
 * the last modified date
 * @member {Date} modified
 */
Metadata.prototype['modified'] = undefined;

/**
 * the unique identifier
 * @member {String} id
 */
Metadata.prototype['id'] = undefined;

/**
 * indicates whether or not this data element is active
 * @member {Boolean} active
 */
Metadata.prototype['active'] = undefined;






export default Metadata;

