# coding: utf-8

"""
    West Coast Informatics Terminology API

    API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>

    The version of the OpenAPI document: 1.0.0
    Contact: info@westcoastinformatics.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 1.10.5, < 2",
    "aenum"
]

setup(
    name=NAME,
    version=VERSION,
    description="West Coast Informatics Terminology API",
    author="API Support",
    author_email="info@westcoastinformatics.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "West Coast Informatics Terminology API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    API documentation for the &lt;a href&#x3D;\&quot;https://www.westcoastinformatics.com\&quot;&gt;West Coast Informatics&lt;/a&gt; terminology server API.&lt;p&gt;Request a 30-day bearer token from &lt;a href&#x3D;\&quot;mailto:info@westcoastinformatics.com\&quot;&gt;info@westcoastinformatics.com&lt;/a&gt;.&lt;/p&gt; &lt;p&gt;For full documentation on this service, please visit our wiki page at &lt;a href&#x3D;\&quot;https://wci-wiki.atlassian.net/wiki/spaces/TSV2\&quot;&gt;https://wci-wiki.atlassian.net/wiki/spaces/TSV2&lt;/a&gt;.&lt;/p&gt;
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
