/*
 * West Coast Informatics Terminology API
 * API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.openapitools.client.model.Atom;
import org.openapitools.client.model.Axiom;
import org.openapitools.client.model.Definition;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents a concept with a code in a terminology
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-13T22:04:29.340934Z[Etc/UTC]")
public class Concept {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_ATOMS = "atoms";
  @SerializedName(SERIALIZED_NAME_ATOMS)
  private List<Atom> atoms = new ArrayList<>();

  public static final String SERIALIZED_NAME_SEMANTIC_TYPES = "semanticTypes";
  @SerializedName(SERIALIZED_NAME_SEMANTIC_TYPES)
  private Set<String> semanticTypes;

  public static final String SERIALIZED_NAME_DEFINITIONS = "definitions";
  @SerializedName(SERIALIZED_NAME_DEFINITIONS)
  private List<Definition> definitions;

  public static final String SERIALIZED_NAME_AXIOMS = "axioms";
  @SerializedName(SERIALIZED_NAME_AXIOMS)
  private List<Axiom> axioms;

  public static final String SERIALIZED_NAME_SUFFICIENTLY_DEFINED = "sufficientlyDefined";
  @SerializedName(SERIALIZED_NAME_SUFFICIENTLY_DEFINED)
  private Boolean sufficientlyDefined;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_LOCAL = "local";
  @SerializedName(SERIALIZED_NAME_LOCAL)
  private Boolean local;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_TERMINOLOGY = "terminology";
  @SerializedName(SERIALIZED_NAME_TERMINOLOGY)
  private String terminology;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Map<String, String> attributes = new HashMap<>();

  public Concept() {
  }

  public Concept code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * the code in the specified terminology
   * @return code
  **/
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Concept atoms(List<Atom> atoms) {
    
    this.atoms = atoms;
    return this;
  }

  public Concept addAtomsItem(Atom atomsItem) {
    if (this.atoms == null) {
      this.atoms = new ArrayList<>();
    }
    this.atoms.add(atomsItem);
    return this;
  }

   /**
   * the names associated with this concept
   * @return atoms
  **/
  @javax.annotation.Nonnull
  public List<Atom> getAtoms() {
    return atoms;
  }


  public void setAtoms(List<Atom> atoms) {
    this.atoms = atoms;
  }


  public Concept semanticTypes(Set<String> semanticTypes) {
    
    this.semanticTypes = semanticTypes;
    return this;
  }

  public Concept addSemanticTypesItem(String semanticTypesItem) {
    if (this.semanticTypes == null) {
      this.semanticTypes = new LinkedHashSet<>();
    }
    this.semanticTypes.add(semanticTypesItem);
    return this;
  }

   /**
   * high-level semantic categories associated with this concept - values depend on the terminologies loaded
   * @return semanticTypes
  **/
  @javax.annotation.Nullable
  public Set<String> getSemanticTypes() {
    return semanticTypes;
  }


  public void setSemanticTypes(Set<String> semanticTypes) {
    this.semanticTypes = semanticTypes;
  }


  public Concept definitions(List<Definition> definitions) {
    
    this.definitions = definitions;
    return this;
  }

  public Concept addDefinitionsItem(Definition definitionsItem) {
    if (this.definitions == null) {
      this.definitions = new ArrayList<>();
    }
    this.definitions.add(definitionsItem);
    return this;
  }

   /**
   * the definitions associated with this concept
   * @return definitions
  **/
  @javax.annotation.Nullable
  public List<Definition> getDefinitions() {
    return definitions;
  }


  public void setDefinitions(List<Definition> definitions) {
    this.definitions = definitions;
  }


  public Concept axioms(List<Axiom> axioms) {
    
    this.axioms = axioms;
    return this;
  }

  public Concept addAxiomsItem(Axiom axiomsItem) {
    if (this.axioms == null) {
      this.axioms = new ArrayList<>();
    }
    this.axioms.add(axiomsItem);
    return this;
  }

   /**
   * the axioms associated with this concept
   * @return axioms
  **/
  @javax.annotation.Nullable
  public List<Axiom> getAxioms() {
    return axioms;
  }


  public void setAxioms(List<Axiom> axioms) {
    this.axioms = axioms;
  }


  public Concept sufficientlyDefined(Boolean sufficientlyDefined) {
    
    this.sufficientlyDefined = sufficientlyDefined;
    return this;
  }

   /**
   * indicates whether the concept is specified with logical necessary and sufficient conditions.  Generally not important except for description-logic based terminologies where this is important.
   * @return sufficientlyDefined
  **/
  @javax.annotation.Nonnull
  public Boolean getSufficientlyDefined() {
    return sufficientlyDefined;
  }


  public void setSufficientlyDefined(Boolean sufficientlyDefined) {
    this.sufficientlyDefined = sufficientlyDefined;
  }


  public Concept created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * the created date
   * @return created
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public Concept local(Boolean local) {
    
    this.local = local;
    return this;
  }

   /**
   * indicates whether this data element was created by local editing
   * @return local
  **/
  @javax.annotation.Nonnull
  public Boolean getLocal() {
    return local;
  }


  public void setLocal(Boolean local) {
    this.local = local;
  }


  public Concept modifiedBy(String modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * the identifier of the user who made the last modification
   * @return modifiedBy
  **/
  @javax.annotation.Nonnull
  public String getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public Concept modified(OffsetDateTime modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * the last modified date
   * @return modified
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getModified() {
    return modified;
  }


  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }


  public Concept id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * the unique identifier
   * @return id
  **/
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public Concept active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * indicates whether or not this data element is active
   * @return active
  **/
  @javax.annotation.Nonnull
  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public Concept terminology(String terminology) {
    
    this.terminology = terminology;
    return this;
  }

   /**
   * the terminology abbreviation
   * @return terminology
  **/
  @javax.annotation.Nonnull
  public String getTerminology() {
    return terminology;
  }


  public void setTerminology(String terminology) {
    this.terminology = terminology;
  }


  public Concept name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * the name
   * @return name
  **/
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Concept attributes(Map<String, String> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public Concept putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * key/value pairs associated with this object. Entries in this map are terminology-specific
   * @return attributes
  **/
  @javax.annotation.Nullable
  public Map<String, String> getAttributes() {
    return attributes;
  }


  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Concept concept = (Concept) o;
    return Objects.equals(this.code, concept.code) &&
        Objects.equals(this.atoms, concept.atoms) &&
        Objects.equals(this.semanticTypes, concept.semanticTypes) &&
        Objects.equals(this.definitions, concept.definitions) &&
        Objects.equals(this.axioms, concept.axioms) &&
        Objects.equals(this.sufficientlyDefined, concept.sufficientlyDefined) &&
        Objects.equals(this.created, concept.created) &&
        Objects.equals(this.local, concept.local) &&
        Objects.equals(this.modifiedBy, concept.modifiedBy) &&
        Objects.equals(this.modified, concept.modified) &&
        Objects.equals(this.id, concept.id) &&
        Objects.equals(this.active, concept.active) &&
        Objects.equals(this.terminology, concept.terminology) &&
        Objects.equals(this.name, concept.name) &&
        Objects.equals(this.attributes, concept.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, atoms, semanticTypes, definitions, axioms, sufficientlyDefined, created, local, modifiedBy, modified, id, active, terminology, name, attributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Concept {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    atoms: ").append(toIndentedString(atoms)).append("\n");
    sb.append("    semanticTypes: ").append(toIndentedString(semanticTypes)).append("\n");
    sb.append("    definitions: ").append(toIndentedString(definitions)).append("\n");
    sb.append("    axioms: ").append(toIndentedString(axioms)).append("\n");
    sb.append("    sufficientlyDefined: ").append(toIndentedString(sufficientlyDefined)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    terminology: ").append(toIndentedString(terminology)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("code");
    openapiFields.add("atoms");
    openapiFields.add("semanticTypes");
    openapiFields.add("definitions");
    openapiFields.add("axioms");
    openapiFields.add("sufficientlyDefined");
    openapiFields.add("created");
    openapiFields.add("local");
    openapiFields.add("modifiedBy");
    openapiFields.add("modified");
    openapiFields.add("id");
    openapiFields.add("active");
    openapiFields.add("terminology");
    openapiFields.add("name");
    openapiFields.add("attributes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("code");
    openapiRequiredFields.add("atoms");
    openapiRequiredFields.add("sufficientlyDefined");
    openapiRequiredFields.add("created");
    openapiRequiredFields.add("local");
    openapiRequiredFields.add("modifiedBy");
    openapiRequiredFields.add("modified");
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("active");
    openapiRequiredFields.add("terminology");
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Concept
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Concept.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Concept is not found in the empty JSON string", Concept.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Concept.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Concept` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Concept.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("atoms").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `atoms` to be an array in the JSON string but got `%s`", jsonObj.get("atoms").toString()));
      }

      JsonArray jsonArrayatoms = jsonObj.getAsJsonArray("atoms");
      // validate the required field `atoms` (array)
      for (int i = 0; i < jsonArrayatoms.size(); i++) {
        Atom.validateJsonElement(jsonArrayatoms.get(i));
      };
      // ensure the optional json data is an array if present
      if (jsonObj.get("semanticTypes") != null && !jsonObj.get("semanticTypes").isJsonNull() && !jsonObj.get("semanticTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `semanticTypes` to be an array in the JSON string but got `%s`", jsonObj.get("semanticTypes").toString()));
      }
      if (jsonObj.get("definitions") != null && !jsonObj.get("definitions").isJsonNull()) {
        JsonArray jsonArraydefinitions = jsonObj.getAsJsonArray("definitions");
        if (jsonArraydefinitions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("definitions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `definitions` to be an array in the JSON string but got `%s`", jsonObj.get("definitions").toString()));
          }

          // validate the optional field `definitions` (array)
          for (int i = 0; i < jsonArraydefinitions.size(); i++) {
            Definition.validateJsonElement(jsonArraydefinitions.get(i));
          };
        }
      }
      if (jsonObj.get("axioms") != null && !jsonObj.get("axioms").isJsonNull()) {
        JsonArray jsonArrayaxioms = jsonObj.getAsJsonArray("axioms");
        if (jsonArrayaxioms != null) {
          // ensure the json data is an array
          if (!jsonObj.get("axioms").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `axioms` to be an array in the JSON string but got `%s`", jsonObj.get("axioms").toString()));
          }

          // validate the optional field `axioms` (array)
          for (int i = 0; i < jsonArrayaxioms.size(); i++) {
            Axiom.validateJsonElement(jsonArrayaxioms.get(i));
          };
        }
      }
      if (!jsonObj.get("modifiedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `modifiedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modifiedBy").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("terminology").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `terminology` to be a primitive type in the JSON string but got `%s`", jsonObj.get("terminology").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Concept.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Concept' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Concept> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Concept.class));

       return (TypeAdapter<T>) new TypeAdapter<Concept>() {
           @Override
           public void write(JsonWriter out, Concept value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Concept read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Concept given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Concept
  * @throws IOException if the JSON string is invalid with respect to Concept
  */
  public static Concept fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Concept.class);
  }

 /**
  * Convert an instance of Concept to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

