/*
 * West Coast Informatics Terminology API
 * API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.client.model.Metadata;
import org.openapitools.client.model.Terminology;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents all types of metadata associated with a terminology
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-13T22:04:29.340934Z[Etc/UTC]")
public class TerminologyMetadata {
  public static final String SERIALIZED_NAME_ATTRIBUTE_NAMES = "attributeNames";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_NAMES)
  private Map<String, Metadata> attributeNames = new HashMap<>();

  public static final String SERIALIZED_NAME_TERMINOLOGY = "terminology";
  @SerializedName(SERIALIZED_NAME_TERMINOLOGY)
  private Terminology terminology;

  public static final String SERIALIZED_NAME_SEMANTIC_TYPES = "semanticTypes";
  @SerializedName(SERIALIZED_NAME_SEMANTIC_TYPES)
  private Map<String, Metadata> semanticTypes = new HashMap<>();

  public static final String SERIALIZED_NAME_ADDITIONAL_RELATIONSHIP_TYPES = "additionalRelationshipTypes";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_RELATIONSHIP_TYPES)
  private Map<String, Metadata> additionalRelationshipTypes = new HashMap<>();

  public static final String SERIALIZED_NAME_RELATIONSHIP_TYPES = "relationshipTypes";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP_TYPES)
  private Map<String, Metadata> relationshipTypes = new HashMap<>();

  public static final String SERIALIZED_NAME_TERM_TYPES = "termTypes";
  @SerializedName(SERIALIZED_NAME_TERM_TYPES)
  private Map<String, Metadata> termTypes = new HashMap<>();

  public static final String SERIALIZED_NAME_LANGUAGES = "languages";
  @SerializedName(SERIALIZED_NAME_LANGUAGES)
  private Map<String, Metadata> languages = new HashMap<>();

  public static final String SERIALIZED_NAME_OTHER = "other";
  @SerializedName(SERIALIZED_NAME_OTHER)
  private Map<String, Metadata> other = new HashMap<>();

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_LOCAL = "local";
  @SerializedName(SERIALIZED_NAME_LOCAL)
  private Boolean local;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public TerminologyMetadata() {
  }

  public TerminologyMetadata attributeNames(Map<String, Metadata> attributeNames) {
    
    this.attributeNames = attributeNames;
    return this;
  }

  public TerminologyMetadata putAttributeNamesItem(String key, Metadata attributeNamesItem) {
    if (this.attributeNames == null) {
      this.attributeNames = new HashMap<>();
    }
    this.attributeNames.put(key, attributeNamesItem);
    return this;
  }

   /**
   * the attribute names used by the terminology
   * @return attributeNames
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getAttributeNames() {
    return attributeNames;
  }


  public void setAttributeNames(Map<String, Metadata> attributeNames) {
    this.attributeNames = attributeNames;
  }


  public TerminologyMetadata terminology(Terminology terminology) {
    
    this.terminology = terminology;
    return this;
  }

   /**
   * Get terminology
   * @return terminology
  **/
  @javax.annotation.Nonnull
  public Terminology getTerminology() {
    return terminology;
  }


  public void setTerminology(Terminology terminology) {
    this.terminology = terminology;
  }


  public TerminologyMetadata semanticTypes(Map<String, Metadata> semanticTypes) {
    
    this.semanticTypes = semanticTypes;
    return this;
  }

  public TerminologyMetadata putSemanticTypesItem(String key, Metadata semanticTypesItem) {
    if (this.semanticTypes == null) {
      this.semanticTypes = new HashMap<>();
    }
    this.semanticTypes.put(key, semanticTypesItem);
    return this;
  }

   /**
   * the semantic types used by the terminology
   * @return semanticTypes
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getSemanticTypes() {
    return semanticTypes;
  }


  public void setSemanticTypes(Map<String, Metadata> semanticTypes) {
    this.semanticTypes = semanticTypes;
  }


  public TerminologyMetadata additionalRelationshipTypes(Map<String, Metadata> additionalRelationshipTypes) {
    
    this.additionalRelationshipTypes = additionalRelationshipTypes;
    return this;
  }

  public TerminologyMetadata putAdditionalRelationshipTypesItem(String key, Metadata additionalRelationshipTypesItem) {
    if (this.additionalRelationshipTypes == null) {
      this.additionalRelationshipTypes = new HashMap<>();
    }
    this.additionalRelationshipTypes.put(key, additionalRelationshipTypesItem);
    return this;
  }

   /**
   * the additional relationship types used by the terminology
   * @return additionalRelationshipTypes
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getAdditionalRelationshipTypes() {
    return additionalRelationshipTypes;
  }


  public void setAdditionalRelationshipTypes(Map<String, Metadata> additionalRelationshipTypes) {
    this.additionalRelationshipTypes = additionalRelationshipTypes;
  }


  public TerminologyMetadata relationshipTypes(Map<String, Metadata> relationshipTypes) {
    
    this.relationshipTypes = relationshipTypes;
    return this;
  }

  public TerminologyMetadata putRelationshipTypesItem(String key, Metadata relationshipTypesItem) {
    if (this.relationshipTypes == null) {
      this.relationshipTypes = new HashMap<>();
    }
    this.relationshipTypes.put(key, relationshipTypesItem);
    return this;
  }

   /**
   * the relationship types used by the terminology
   * @return relationshipTypes
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getRelationshipTypes() {
    return relationshipTypes;
  }


  public void setRelationshipTypes(Map<String, Metadata> relationshipTypes) {
    this.relationshipTypes = relationshipTypes;
  }


  public TerminologyMetadata termTypes(Map<String, Metadata> termTypes) {
    
    this.termTypes = termTypes;
    return this;
  }

  public TerminologyMetadata putTermTypesItem(String key, Metadata termTypesItem) {
    if (this.termTypes == null) {
      this.termTypes = new HashMap<>();
    }
    this.termTypes.put(key, termTypesItem);
    return this;
  }

   /**
   * the term types used by the terminology
   * @return termTypes
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getTermTypes() {
    return termTypes;
  }


  public void setTermTypes(Map<String, Metadata> termTypes) {
    this.termTypes = termTypes;
  }


  public TerminologyMetadata languages(Map<String, Metadata> languages) {
    
    this.languages = languages;
    return this;
  }

  public TerminologyMetadata putLanguagesItem(String key, Metadata languagesItem) {
    if (this.languages == null) {
      this.languages = new HashMap<>();
    }
    this.languages.put(key, languagesItem);
    return this;
  }

   /**
   * the languages used by the terminology
   * @return languages
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getLanguages() {
    return languages;
  }


  public void setLanguages(Map<String, Metadata> languages) {
    this.languages = languages;
  }


  public TerminologyMetadata other(Map<String, Metadata> other) {
    
    this.other = other;
    return this;
  }

  public TerminologyMetadata putOtherItem(String key, Metadata otherItem) {
    if (this.other == null) {
      this.other = new HashMap<>();
    }
    this.other.put(key, otherItem);
    return this;
  }

   /**
   * miscellaneous terminology metadata (terminology-specific)
   * @return other
  **/
  @javax.annotation.Nullable
  public Map<String, Metadata> getOther() {
    return other;
  }


  public void setOther(Map<String, Metadata> other) {
    this.other = other;
  }


  public TerminologyMetadata created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * the created date
   * @return created
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public TerminologyMetadata local(Boolean local) {
    
    this.local = local;
    return this;
  }

   /**
   * indicates whether this data element was created by local editing
   * @return local
  **/
  @javax.annotation.Nonnull
  public Boolean getLocal() {
    return local;
  }


  public void setLocal(Boolean local) {
    this.local = local;
  }


  public TerminologyMetadata modifiedBy(String modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * the identifier of the user who made the last modification
   * @return modifiedBy
  **/
  @javax.annotation.Nonnull
  public String getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public TerminologyMetadata modified(OffsetDateTime modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * the last modified date
   * @return modified
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getModified() {
    return modified;
  }


  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }


  public TerminologyMetadata id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * the unique identifier
   * @return id
  **/
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public TerminologyMetadata active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * indicates whether or not this data element is active
   * @return active
  **/
  @javax.annotation.Nonnull
  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerminologyMetadata terminologyMetadata = (TerminologyMetadata) o;
    return Objects.equals(this.attributeNames, terminologyMetadata.attributeNames) &&
        Objects.equals(this.terminology, terminologyMetadata.terminology) &&
        Objects.equals(this.semanticTypes, terminologyMetadata.semanticTypes) &&
        Objects.equals(this.additionalRelationshipTypes, terminologyMetadata.additionalRelationshipTypes) &&
        Objects.equals(this.relationshipTypes, terminologyMetadata.relationshipTypes) &&
        Objects.equals(this.termTypes, terminologyMetadata.termTypes) &&
        Objects.equals(this.languages, terminologyMetadata.languages) &&
        Objects.equals(this.other, terminologyMetadata.other) &&
        Objects.equals(this.created, terminologyMetadata.created) &&
        Objects.equals(this.local, terminologyMetadata.local) &&
        Objects.equals(this.modifiedBy, terminologyMetadata.modifiedBy) &&
        Objects.equals(this.modified, terminologyMetadata.modified) &&
        Objects.equals(this.id, terminologyMetadata.id) &&
        Objects.equals(this.active, terminologyMetadata.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeNames, terminology, semanticTypes, additionalRelationshipTypes, relationshipTypes, termTypes, languages, other, created, local, modifiedBy, modified, id, active);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminologyMetadata {\n");
    sb.append("    attributeNames: ").append(toIndentedString(attributeNames)).append("\n");
    sb.append("    terminology: ").append(toIndentedString(terminology)).append("\n");
    sb.append("    semanticTypes: ").append(toIndentedString(semanticTypes)).append("\n");
    sb.append("    additionalRelationshipTypes: ").append(toIndentedString(additionalRelationshipTypes)).append("\n");
    sb.append("    relationshipTypes: ").append(toIndentedString(relationshipTypes)).append("\n");
    sb.append("    termTypes: ").append(toIndentedString(termTypes)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attributeNames");
    openapiFields.add("terminology");
    openapiFields.add("semanticTypes");
    openapiFields.add("additionalRelationshipTypes");
    openapiFields.add("relationshipTypes");
    openapiFields.add("termTypes");
    openapiFields.add("languages");
    openapiFields.add("other");
    openapiFields.add("created");
    openapiFields.add("local");
    openapiFields.add("modifiedBy");
    openapiFields.add("modified");
    openapiFields.add("id");
    openapiFields.add("active");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("terminology");
    openapiRequiredFields.add("created");
    openapiRequiredFields.add("local");
    openapiRequiredFields.add("modifiedBy");
    openapiRequiredFields.add("modified");
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("active");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TerminologyMetadata
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TerminologyMetadata.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TerminologyMetadata is not found in the empty JSON string", TerminologyMetadata.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TerminologyMetadata.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TerminologyMetadata` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TerminologyMetadata.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `terminology`
      Terminology.validateJsonElement(jsonObj.get("terminology"));
      if (!jsonObj.get("modifiedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `modifiedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modifiedBy").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TerminologyMetadata.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TerminologyMetadata' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TerminologyMetadata> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TerminologyMetadata.class));

       return (TypeAdapter<T>) new TypeAdapter<TerminologyMetadata>() {
           @Override
           public void write(JsonWriter out, TerminologyMetadata value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TerminologyMetadata read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TerminologyMetadata given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TerminologyMetadata
  * @throws IOException if the JSON string is invalid with respect to TerminologyMetadata
  */
  public static TerminologyMetadata fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TerminologyMetadata.class);
  }

 /**
  * Convert an instance of TerminologyMetadata to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

