# coding: utf-8

"""
    West Coast Informatics Terminology API

    API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>

    The version of the OpenAPI document: 1.0.0
    Contact: info@westcoastinformatics.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.atom import Atom  # noqa: E501

class TestAtom(unittest.TestCase):
    """Atom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Atom:
        """Test Atom
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Atom`
        """
        model = Atom()  # noqa: E501
        if include_optional:
            return Atom(
                code_id = 'e.g. 404684003 in SNOMEDCT, or 1191 in RXNORM, or 2951-2 in LNC',
                locale_map = {"en":true,"en_GB":false},
                concept_id = 'e.g. 404684003 in SNOMEDCT',
                descriptor_id = 'e.g. D001241 in MSH',
                term_type = 'e.g. PT or 900000000000013009',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                local = True,
                modified_by = '',
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                active = True,
                name = '',
                terminology_id = '',
                terminology = '',
                attributes = {
                    'key' : ''
                    }
            )
        else:
            return Atom(
                code_id = 'e.g. 404684003 in SNOMEDCT, or 1191 in RXNORM, or 2951-2 in LNC',
                locale_map = {"en":true,"en_GB":false},
                term_type = 'e.g. PT or 900000000000013009',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                local = True,
                modified_by = '',
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                active = True,
                name = '',
                terminology = '',
        )
        """

    def testAtom(self):
        """Test Atom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
