# coding: utf-8

"""
    West Coast Informatics Terminology API

    API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>

    The version of the OpenAPI document: 1.0.0
    Contact: info@westcoastinformatics.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class Atom(BaseModel):
    """
    Represents a name with a term type that contributes meaning to a concept
    """
    code_id: StrictStr = Field(..., alias="codeId", description="the code in the specified terminology")
    locale_map: Dict[str, StrictBool] = Field(..., alias="localeMap", description="a map of language codes to boolean values indicated whether this definition is preferred in that language context")
    concept_id: Optional[StrictStr] = Field(None, alias="conceptId", description="the concept id (for terminologies that use concepts)")
    descriptor_id: Optional[StrictStr] = Field(None, alias="descriptorId", description="the descriptor id (for terminologies that use descriptors)")
    term_type: StrictStr = Field(..., alias="termType", description="the term type")
    created: datetime = Field(..., description="the created date")
    local: StrictBool = Field(..., description="indicates whether this data element was created by local editing")
    modified_by: StrictStr = Field(..., alias="modifiedBy", description="the identifier of the user who made the last modification")
    modified: datetime = Field(..., description="the last modified date")
    id: StrictStr = Field(..., description="the unique identifier")
    active: StrictBool = Field(..., description="indicates whether or not this data element is active")
    name: StrictStr = Field(..., description="the name")
    terminology_id: Optional[StrictStr] = Field(None, alias="terminologyId", description="the identifier asserted by the terminology")
    terminology: StrictStr = Field(..., description="the terminology abbreviation")
    attributes: Optional[Dict[str, StrictStr]] = Field(None, description="key/value pairs associated with this object. Entries in this map are terminology-specific")
    __properties = ["codeId", "localeMap", "conceptId", "descriptorId", "termType", "created", "local", "modifiedBy", "modified", "id", "active", "name", "terminologyId", "terminology", "attributes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Atom:
        """Create an instance of Atom from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Atom:
        """Create an instance of Atom from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Atom.parse_obj(obj)

        _obj = Atom.parse_obj({
            "code_id": obj.get("codeId"),
            "locale_map": obj.get("localeMap"),
            "concept_id": obj.get("conceptId"),
            "descriptor_id": obj.get("descriptorId"),
            "term_type": obj.get("termType"),
            "created": obj.get("created"),
            "local": obj.get("local"),
            "modified_by": obj.get("modifiedBy"),
            "modified": obj.get("modified"),
            "id": obj.get("id"),
            "active": obj.get("active"),
            "name": obj.get("name"),
            "terminology_id": obj.get("terminologyId"),
            "terminology": obj.get("terminology"),
            "attributes": obj.get("attributes")
        })
        return _obj


