# coding: utf-8

# flake8: noqa

"""
    West Coast Informatics Terminology API

    API documentation for the <a href=\"https://www.westcoastinformatics.com\">West Coast Informatics</a> terminology server API.<p>Request a 30-day bearer token from <a href=\"mailto:info@westcoastinformatics.com\">info@westcoastinformatics.com</a>.</p> <p>For full documentation on this service, please visit our wiki page at <a href=\"https://wci-wiki.atlassian.net/wiki/spaces/TSV2\">https://wci-wiki.atlassian.net/wiki/spaces/TSV2</a>.</p>

    The version of the OpenAPI document: 1.0.0
    Contact: info@westcoastinformatics.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.login_api import LoginApi
from openapi_client.api.terminology_api import TerminologyApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.atom import Atom
from openapi_client.models.auth_request import AuthRequest
from openapi_client.models.auth_response import AuthResponse
from openapi_client.models.axiom import Axiom
from openapi_client.models.concept import Concept
from openapi_client.models.concept_relationship import ConceptRelationship
from openapi_client.models.concept_tree_position import ConceptTreePosition
from openapi_client.models.definition import Definition
from openapi_client.models.mapping import Mapping
from openapi_client.models.mapset import Mapset
from openapi_client.models.metadata import Metadata
from openapi_client.models.result_list_concept import ResultListConcept
from openapi_client.models.result_list_concept_relationship import ResultListConceptRelationship
from openapi_client.models.result_list_concept_tree_position import ResultListConceptTreePosition
from openapi_client.models.result_list_mapping import ResultListMapping
from openapi_client.models.result_list_mapset import ResultListMapset
from openapi_client.models.result_list_subset import ResultListSubset
from openapi_client.models.subset import Subset
from openapi_client.models.terminology import Terminology
from openapi_client.models.terminology_metadata import TerminologyMetadata
